// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Migrate needs a non-pooled connection (advisory locks, DDL) — use Supabase's
  // direct connection here, not the PgBouncer pooled one the app uses at runtime.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
