import { createServerClient } from "@supabase/ssr";
import { NextResponse, type NextRequest } from "next/server";

// Explicit allowlist — anything NOT listed here is private by default and
// redirects to /login when signed out. Add new public routes here deliberately;
// do not flip this to a denylist.
//
// PUBLIC (no auth):
//   /              landing page
//   /login
//   /catalog       Phase 2 — public catalog browse (/catalog) + detail (/catalog/[id])
//   /robots.txt    generated by src/app/robots.ts
//   /sitemap.xml   generated by src/app/sitemap.ts
//
// robots.txt and sitemap.xml are matched by the config below (it only skips
// _next assets and image extensions), so without an entry here a crawler
// fetching either one would be redirected to /login and the catalog would
// never be indexed.
//
// PROTECTED (everything else, by omission), currently:
//   /dashboard
//   /products (and subroutes: /products/new, /products/[id], /products/[id]/edit)
//   /suppliers
//   /import
//   /inquiries
//   /staff                     owner-only (checked in the page, not here)
//   /force-password-change     authenticated, but only reachable while
//                              must_change_password is set (see below)

// Exact-match roots (checked with `===`, never a prefix — "/" must not swallow
// every other route).
const PUBLIC_EXACT_PATHS = ["/", "/login", "/robots.txt", "/sitemap.xml"];

// Prefix paths for whole public sub-trees. "/catalog" here already covers
// "/catalog/[id]" once that route exists — no separate entry needed.
const PUBLIC_PREFIX_PATHS = ["/catalog"];

function isPublicPath(pathname: string): boolean {
  if (PUBLIC_EXACT_PATHS.includes(pathname)) return true;
  return PUBLIC_PREFIX_PATHS.some((path) => pathname.startsWith(path));
}

export async function updateSession(request: NextRequest) {
  let supabaseResponse = NextResponse.next({ request });

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!,
    {
      cookies: {
        getAll() {
          return request.cookies.getAll();
        },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value }) => request.cookies.set(name, value));
          supabaseResponse = NextResponse.next({ request });
          cookiesToSet.forEach(({ name, value, options }) =>
            supabaseResponse.cookies.set(name, value, options),
          );
        },
      },
    },
  );

  // Do not remove: this call refreshes the auth token and is what actually
  // keeps sessions alive. Without it the client above is inert.
  const {
    data: { user },
  } = await supabase.auth.getUser();

  const pathname = request.nextUrl.pathname;

  if (!user && !isPublicPath(pathname)) {
    const url = request.nextUrl.clone();
    url.pathname = "/login";
    url.searchParams.set("next", pathname);
    return NextResponse.redirect(url);
  }

  if (user && pathname === "/login") {
    const url = request.nextUrl.clone();
    url.pathname = "/dashboard";
    return NextResponse.redirect(url);
  }

  // Staff accounts are created with a temp password and this flag set —
  // only the admin API (never the user's own session) can clear it, so it's
  // tamper-proof from the client. Block every other route until it's clear.
  const mustChangePassword = Boolean(user?.app_metadata?.must_change_password);
  if (user && mustChangePassword && pathname !== "/force-password-change") {
    const url = request.nextUrl.clone();
    url.pathname = "/force-password-change";
    return NextResponse.redirect(url);
  }
  if (user && !mustChangePassword && pathname === "/force-password-change") {
    const url = request.nextUrl.clone();
    url.pathname = "/dashboard";
    return NextResponse.redirect(url);
  }

  return supabaseResponse;
}
